# Site settings
title: George Banis
email: gbanis@gmail.com
description:  George Banis is a full-stack engineer, currently progamming in Javascript and Ruby. In this blog he talks about software engineering, architecture, and performance.
baseurl: "" # the subpath of your site, e.g. /blog/
keywords: web developer, software engineer, programming, javascript, reactjs, ruby, ruby on rails
url: "http://gbanis.com" # the base hostname & protocol for your site
location: Boston, MA

# Social Media Profiles
twitter_username:   gbanis
github_username:    gbanis
linkedin_username:  gbanis
# skype_username:     georgebanis

# Outputting
permalink: /blog/:title

# Build settings
# markdown: kramdown
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
highlighter: pygments


# Creates a standards compliant sitemap
gems:
  - jekyll-sitemap

exclude: [Gemfile, Rakefile, Gemfile.lock, README.md, config.rb]

